****** PART ******

In [1]:
import pandas as pd

In [2]:
pd.__version__   #double underscore

'2.3.3'

In [3]:
lst = [1,2,3,4,5,6]
print(lst)

[1, 2, 3, 4, 5, 6]

In [4]:
series = pd.Series(lst)  # create Series of panda and it store in store
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
empty = pd.Series([]) # now create empty series and don't have to provide anything into series argument
empty

Series([], dtype: object)

In [6]:
a = pd.Series(["p","q","r","s","t"], index = [10,11,12,13,14]) #  10...14 index value ,p...t  coln data "a" is panda series
a

10    p
11    q
12    r
13    s
14    t
dtype: object

In [7]:
b = pd.Series(["p","q","r","s","t"], index = [10,11,12,13,14] ,name = "alphabets") # name of the series
b

10    p
11    q
12    r
13    s
14    t
Name: alphabets, dtype: object

In [8]:
scalar_series = pd.Series(0.5) # create a scalar series and provide a scalar value
scalar_series

0    0.5
dtype: float64

In [9]:
scalar_series = pd.Series(0.5,index = [1,2,3])   # increase tha quantity of this scalar value
scalar_series

1    0.5
2    0.5
3    0.5
dtype: float64

In [10]:
dict_series = pd.Series({"p":1,"q":2,"r":3,"s":4,"t":5}) #create panda series using dictionary
dict_series

p    1
q    2
r    3
s    4
t    5
dtype: int64

In [11]:
dict_series[0] # if printed index 0 value thn getting 1

C:\Users\Dr.Sumedha\AppData\Local\Temp\ipykernel_3516\172705971.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dict_series[0] # if printed index 0 value thn getting 1

np.int64(1)

In [12]:
dict_series[0:3]  # if print data from 0 to 2

p    1
q    2
r    3
dtype: int64

#Pandas DataFrame

In [13]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

#DataFrame Using List

In [14]:
list = [1,2,3,4,5]
df = pd.DataFrame(list)
df

   0
0  1
1  2
2  3
3  4
4  5

In [15]:
list = [[1,2,3,4,5],[11,12,13,14,15]] # 3 Two row 5 coln
df = pd.DataFrame(list) 
df

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [16]:
a = [{"a":5,"b":7,"c":9,"d":2},{"a":4,"b":8,"c":19,"d":12}]  #Dictionary keys represents Column names
df = pd.DataFrame(a)
df

   a  b   c   d
0  5  7   9   2
1  4  8  19  12

In [17]:
b = {"RollNo":pd.Series([1,2,3,4,5]),"Math":pd.Series([23,45,67,89,12]),"Physics":pd.Series([34,56,78,24,46])}
df = pd.DataFrame(b)
df

   RollNo  Math  Physics
0       1    23       34
1       2    45       56
2       3    67       78
3       4    89       24
4       5    12       46

reading CSV (Common Separated Values) as DataFrames

In [18]:
df = pd.read_csv
df

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'>

In [19]:
import pandas as pd 
import os

In [20]:
os.getcwd()

'c:\\Users\\Dr.Sumedha\\Desktop\\New folder'

In [21]:
import pandas as pd 
import os
os.getcwd()

'c:\\Users\\Dr.Sumedha\\Desktop\\New folder'

#DataFrame Functions

In [22]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\Salary_Data.csv")

df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [23]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [24]:
df.shape

(30, 2)

In [25]:
df.size  # 30 * 2

60

In [26]:
df.head()  # It gives tha first five rows .It tells how data cell is going looks like

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [27]:
df.head(2) #First two rows

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0

In [28]:
df.tail() # Gives last five rows

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [29]:
df.tail(8) # give last 8 rows of data

    YearsExperience    Salary
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [30]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [31]:
df.info() # Give some information of DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [32]:
df2 = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample2.csv")
df2.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [33]:
df2 =  pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\Restaurant.csv")
df2.head

<bound method NDFrame.head of      Rank           Restaurant  \
0       1           McDonald's
1       2            Starbucks
2       3          Chick-fil-A
3       4            Taco Bell
4       5          Burger King
..    ...                  ...
245   246      Rainforest Cafe
246   247                  PDQ
247   248        Lupe Tortilla
248   249  Cook-Out Restaurant
249   250             Jollibee

                                               Content  Sales YOY_Sales  \
0                                                  NaN  40412      4.9%
1                                                  NaN  21380      8.6%
2    While Popeyes got a lot of the chicken buzz in...  11320     13.0%
3                                                  NaN  11293      9.0%
4                                                  NaN  10204      2.7%
..                                                 ...    ...       ...
245                                                NaN    129    -10.4%
246                                                NaN    127     -5.5%
247                                                NaN    127     12.1%
248                                                NaN    126     10.1%
249                                                NaN    126     15.2%

     Units YOY_Units Headquarters             Segment_Category
0    13846     -0.5%          NaN       Quick Service & Burger
1    15049      3.0%          NaN  Quick Service & Coffee Cafe
2     2470      5.0%          NaN      Quick Service & Chicken
3     6766      2.7%          NaN      Quick Service & Mexican
4     7346      0.2%          NaN       Quick Service & Burger
..     ...       ...          ...                          ...
245     18     -5.3%          NaN                  Varied Menu
246     56    -11.1%          NaN                      Chicken
247     25      8.7%          NaN                      Mexican
248    270      7.1%          NaN                       Burger
249     40     11.1%          NaN                      Chicken

[250 rows x 9 columns]>

In [34]:
df2.shape # 250 rows and 9 coln

(250, 9)

In [35]:
df2.info() # how many null values are there

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              250 non-null    int64
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB

In [36]:
df2.describe() #

             Rank        Sales         Units
count  250.000000    250.00000    250.000000
mean   125.500000   1242.74000    850.076000
std     72.312977   3365.22882   2296.151659
min      1.000000    126.00000     13.000000
25%     63.250000    181.00000     85.000000
50%    125.500000    330.00000    207.000000
75%    187.750000    724.75000    555.250000
max    250.000000  40412.00000  23801.000000

*** PART 4 ***

# Handling Missing Values

In [37]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample.csv")
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [38]:
df.isnull() # If the cell consist of the null value thn it is going to show true otherwise it is going to show false.

    Roll No.  Physics  Chemistry  Maths  Computer
0      False    False      False  False     False
1      False    False      False  False     False
2      False    False      False  False     False
3      False    False      False  False     False
4      False    False      False  False     False
5      False    False       True  False     False
6      False    False      False  False     False
7      False    False      False  False     False
8      False     True      False  False     False
9      False    False      False  False     False
10     False     True      False  False     False
11     False    False       True  False     False
12     False    False      False  False     False
13     False    False       True   True     False
14     False     True      False  False     False
15     False    False      False  False     False
16     False    False      False  False     False
17     False    False      False  False     False
18     False    False      False  False     False
19     False    False      False  False     False
20     False    False      False  False     False
21     False    False      False  False     False
22     False    False      False  False     False
23     False    False      False  False     False
24     False    False       True   True     False
25     False    False      False  False     False
26     False    False      False  False     False
27     False    False      False  False      True
28     False    False      False  False     False
29     False    False      False  False     False

In [39]:
df.isnull().sum() # that is add all the null value .null value of phy is 3 etc.......

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [40]:
df.isnull().sum().sum() # total of all this above null values (0+3+4+2+1)

np.int64(10)

# Dropping Rows with NaN values

In [41]:
df.shape

(30, 5)

In [42]:
df2 = df.dropna(axis = 1)   # which coln is null thn drop it.

In [43]:
df2.shape

(30, 1)

# Dropping Columns with NaN values

In [44]:
df3 = df.dropna(axis = 1) # axis  = 1 for columns

In [45]:
df3.shape

(30, 1)

In [46]:
df.dropna(how = "any") # if any row value is null then remove that row.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
9         10     45.0       16.0   17.0      18.0
12        13     22.0       23.0   24.0      25.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [47]:
df.dropna(how = "all") # If all row values is null then remove that row.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [48]:
df.dropna(inplace = True) #Original data frame will be loss and new data frame will be created, which is replace the original dataframe and that data frame will  not be having any null values.

In [49]:
df.shape # original data frane having 30 rows and 5 colns.

(22, 5)

# *** PART 5 ***

# Filling the Null Values

In [50]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample.csv")
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [51]:
df.isnull()

    Roll No.  Physics  Chemistry  Maths  Computer
0      False    False      False  False     False
1      False    False      False  False     False
2      False    False      False  False     False
3      False    False      False  False     False
4      False    False      False  False     False
5      False    False       True  False     False
6      False    False      False  False     False
7      False    False      False  False     False
8      False     True      False  False     False
9      False    False      False  False     False
10     False     True      False  False     False
11     False    False       True  False     False
12     False    False      False  False     False
13     False    False       True   True     False
14     False     True      False  False     False
15     False    False      False  False     False
16     False    False      False  False     False
17     False    False      False  False     False
18     False    False      False  False     False
19     False    False      False  False     False
20     False    False      False  False     False
21     False    False      False  False     False
22     False    False      False  False     False
23     False    False      False  False     False
24     False    False       True   True     False
25     False    False      False  False     False
26     False    False      False  False     False
27     False    False      False  False      True
28     False    False      False  False     False
29     False    False      False  False     False

In [52]:
df.isnull().sum() # Give number of null values each and every coln individually.

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [53]:
df.fillna(2)  # Jo vi null value hain woh 0 ya 2 ya kuch aur se fill kar sakte hain .

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        2.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      2.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      2.0       17.0   18.0      19.0
11        12     88.0        2.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        2.0    2.0      42.0
14        15      2.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        2.0    2.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       2.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [54]:
df.fillna({"Physics" : "none","Chemistry" : 0,"Maths" :30,"Computer" : "!"})    # We can fill different different thing

    Roll No. Physics  Chemistry  Maths Computer
0          1    56.0       57.0   58.0     59.0
1          2    23.0       24.0   25.0     26.0
2          3    89.0       25.0   26.0     27.0
3          4    45.0       26.0   27.0     28.0
4          5    23.0       27.0   28.0     29.0
5          6    90.0        0.0   29.0     30.0
6          7    12.0       13.0   14.0     15.0
7          8    78.0       14.0   15.0     16.0
8          9    none       15.0   16.0     17.0
9         10    45.0       16.0   17.0     18.0
10        11    none       17.0   18.0     19.0
11        12    88.0        0.0   19.0     20.0
12        13    22.0       23.0   24.0     25.0
13        14    90.0        0.0   30.0     42.0
14        15    none       43.0   43.0     43.0
15        16    44.0       44.0   44.0     44.0
16        17    45.0       45.0   45.0     45.0
17        18    46.0       46.0   46.0     46.0
18        19    47.0       47.0   47.0     47.0
19        20    48.0       48.0   48.0     48.0
20        21    49.0       49.0   49.0     49.0
21        22    50.0       50.0   50.0     50.0
22        23    51.0       51.0   51.0     51.0
23        24    52.0       52.0   52.0     52.0
24        25    53.0        0.0   30.0     53.0
25        26    54.0       33.0   33.0     54.0
26        27    55.0       34.0   34.0     55.0
27        28    56.0       35.0   35.0        !
28        29    57.0       36.0   36.0     66.0
29        30    58.0       37.0   37.0     43.0

In [55]:
df.fillna(method = "ffill",axis = 1) # All the null value will be filled in the just previous value . axis  = 1 likhne se jo null value hain woh fill hota hain just previous coln se.

C:\Users\Dr.Sumedha\AppData\Local\Temp\ipykernel_3516\7305784.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill",axis = 1) # All the null value will be filled in the just previous value . axis  = 1 likhne se jo null value hain woh fill hota hain just previous coln se.

    Roll No.  Physics  Chemistry  Maths  Computer
0        1.0     56.0       57.0   58.0      59.0
1        2.0     23.0       24.0   25.0      26.0
2        3.0     89.0       25.0   26.0      27.0
3        4.0     45.0       26.0   27.0      28.0
4        5.0     23.0       27.0   28.0      29.0
5        6.0     90.0       90.0   29.0      30.0
6        7.0     12.0       13.0   14.0      15.0
7        8.0     78.0       14.0   15.0      16.0
8        9.0      9.0       15.0   16.0      17.0
9       10.0     45.0       16.0   17.0      18.0
10      11.0     11.0       17.0   18.0      19.0
11      12.0     88.0       88.0   19.0      20.0
12      13.0     22.0       23.0   24.0      25.0
13      14.0     90.0       90.0   90.0      42.0
14      15.0     15.0       43.0   43.0      43.0
15      16.0     44.0       44.0   44.0      44.0
16      17.0     45.0       45.0   45.0      45.0
17      18.0     46.0       46.0   46.0      46.0
18      19.0     47.0       47.0   47.0      47.0
19      20.0     48.0       48.0   48.0      48.0
20      21.0     49.0       49.0   49.0      49.0
21      22.0     50.0       50.0   50.0      50.0
22      23.0     51.0       51.0   51.0      51.0
23      24.0     52.0       52.0   52.0      52.0
24      25.0     53.0       53.0   53.0      53.0
25      26.0     54.0       33.0   33.0      54.0
26      27.0     55.0       34.0   34.0      55.0
27      28.0     56.0       35.0   35.0      35.0
28      29.0     57.0       36.0   36.0      66.0
29      30.0     58.0       37.0   37.0      43.0

In [56]:
df["Physics"].fillna(value = df["Physics"].mean()) # I am going to find the avg marks of physics of complete class and i am going to fill those marks at the null values .45 which is avg of all this marks so we can fill the null value with the mean.

0     56.000000
1     23.000000
2     89.000000
3     45.000000
4     23.000000
5     90.000000
6     12.000000
7     78.000000
8     52.814815
9     45.000000
10    52.814815
11    88.000000
12    22.000000
13    90.000000
14    52.814815
15    44.000000
16    45.000000
17    46.000000
18    47.000000
19    48.000000
20    49.000000
21    50.000000
22    51.000000
23    52.000000
24    53.000000
25    54.000000
26    55.000000
27    56.000000
28    57.000000
29    58.000000
Name: Physics, dtype: float64

In [57]:
df.fillna(method = "bfill",inplace  = True) # backward fill -> fill the null value with  the next value not previous . If provide inplace  = True then it is going to replace the original DataFrame.
df

C:\Users\Dr.Sumedha\AppData\Local\Temp\ipykernel_3516\3452335393.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "bfill",inplace  = True) # backward fill -> fill the null value with  the next value not previous . If provide inplace  = True then it is going to replace the original DataFrame.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       13.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     45.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     88.0       17.0   18.0      19.0
11        12     88.0       23.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       43.0   43.0      42.0
14        15     44.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       33.0   33.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      66.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

# *** PART 6 ***

In [58]:
# Replace()

In [59]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample.csv")
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [60]:
df.replace(to_replace = 27,value = 30)

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      30.0
3          4     45.0       26.0   30.0      28.0
4          5     23.0       30.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        30     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [61]:
df.replace(34,10000)

    Roll No.  Physics  Chemistry    Maths  Computer
0          1     56.0       57.0     58.0      59.0
1          2     23.0       24.0     25.0      26.0
2          3     89.0       25.0     26.0      27.0
3          4     45.0       26.0     27.0      28.0
4          5     23.0       27.0     28.0      29.0
5          6     90.0        NaN     29.0      30.0
6          7     12.0       13.0     14.0      15.0
7          8     78.0       14.0     15.0      16.0
8          9      NaN       15.0     16.0      17.0
9         10     45.0       16.0     17.0      18.0
10        11      NaN       17.0     18.0      19.0
11        12     88.0        NaN     19.0      20.0
12        13     22.0       23.0     24.0      25.0
13        14     90.0        NaN      NaN      42.0
14        15      NaN       43.0     43.0      43.0
15        16     44.0       44.0     44.0      44.0
16        17     45.0       45.0     45.0      45.0
17        18     46.0       46.0     46.0      46.0
18        19     47.0       47.0     47.0      47.0
19        20     48.0       48.0     48.0      48.0
20        21     49.0       49.0     49.0      49.0
21        22     50.0       50.0     50.0      50.0
22        23     51.0       51.0     51.0      51.0
23        24     52.0       52.0     52.0      52.0
24        25     53.0        NaN      NaN      53.0
25        26     54.0       33.0     33.0      54.0
26        27     55.0    10000.0  10000.0      55.0
27        28     56.0       35.0     35.0       NaN
28        29     57.0       36.0     36.0      66.0
29        30     58.0       37.0     37.0      43.0

In [62]:
df.replace(to_replace = [23,24,25,26], value = "B")

   Roll No. Physics Chemistry Maths Computer
0         1    56.0      57.0  58.0     59.0
1         2       B         B     B        B
2         3    89.0         B     B     27.0
3         4    45.0         B  27.0     28.0
4         5       B      27.0  28.0     29.0
5         6    90.0       NaN  29.0     30.0
6         7    12.0      13.0  14.0     15.0
7         8    78.0      14.0  15.0     16.0
8         9     NaN      15.0  16.0     17.0
9        10    45.0      16.0  17.0     18.0
10       11     NaN      17.0  18.0     19.0
11       12    88.0       NaN  19.0     20.0
12       13    22.0         B     B        B
13       14    90.0       NaN   NaN     42.0
14       15     NaN      43.0  43.0     43.0
15       16    44.0      44.0  44.0     44.0
16       17    45.0      45.0  45.0     45.0
17       18    46.0      46.0  46.0     46.0
18       19    47.0      47.0  47.0     47.0
19       20    48.0      48.0  48.0     48.0
20       21    49.0      49.0  49.0     49.0
21       22    50.0      50.0  50.0     50.0
22        B    51.0      51.0  51.0     51.0
23        B    52.0      52.0  52.0     52.0
24        B    53.0       NaN   NaN     53.0
25        B    54.0      33.0  33.0     54.0
26       27    55.0      34.0  34.0     55.0
27       28    56.0      35.0  35.0      NaN
28       29    57.0      36.0  36.0     66.0
29       30    58.0      37.0  37.0     43.0

In [63]:
df.replace(to_replace = [23,24,25,26],value=["A","B","C","D"])

   Roll No. Physics Chemistry Maths Computer
0         1    56.0      57.0  58.0     59.0
1         2       A         B     C        D
2         3    89.0         C     D     27.0
3         4    45.0         D  27.0     28.0
4         5       A      27.0  28.0     29.0
5         6    90.0       NaN  29.0     30.0
6         7    12.0      13.0  14.0     15.0
7         8    78.0      14.0  15.0     16.0
8         9     NaN      15.0  16.0     17.0
9        10    45.0      16.0  17.0     18.0
10       11     NaN      17.0  18.0     19.0
11       12    88.0       NaN  19.0     20.0
12       13    22.0         A     B        C
13       14    90.0       NaN   NaN     42.0
14       15     NaN      43.0  43.0     43.0
15       16    44.0      44.0  44.0     44.0
16       17    45.0      45.0  45.0     45.0
17       18    46.0      46.0  46.0     46.0
18       19    47.0      47.0  47.0     47.0
19       20    48.0      48.0  48.0     48.0
20       21    49.0      49.0  49.0     49.0
21       22    50.0      50.0  50.0     50.0
22        A    51.0      51.0  51.0     51.0
23        B    52.0      52.0  52.0     52.0
24        C    53.0       NaN   NaN     53.0
25        D    54.0      33.0  33.0     54.0
26       27    55.0      34.0  34.0     55.0
27       28    56.0      35.0  35.0      NaN
28       29    57.0      36.0  36.0     66.0
29       30    58.0      37.0  37.0     43.0

In [64]:
df["Physics"].replace(to_replace = [56,23,89,45],value = ["A","B","C","D"])

0        A
1        B
2        C
3        D
4        B
5     90.0
6     12.0
7     78.0
8      NaN
9        D
10     NaN
11    88.0
12    22.0
13    90.0
14     NaN
15    44.0
16       D
17    46.0
18    47.0
19    48.0
20    49.0
21    50.0
22    51.0
23    52.0
24    53.0
25    54.0
26    55.0
27       A
28    57.0
29    58.0
Name: Physics, dtype: object

In [65]:
df.replace('[A-Za-z]',0, regex = True) # All string characters will be replace with zeros.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [66]:
df.replace(to_replace = 15, method = "ffill") # In row number 8, 15 is replaced by 14.

C:\Users\Dr.Sumedha\AppData\Local\Temp\ipykernel_3516\2551913708.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(to_replace = 15, method = "ffill") # In row number 8, 15 is replaced by 14.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      30.0
7          8     78.0       14.0   14.0      16.0
8          9      NaN       14.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        14      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [67]:
df.replace(to_replace = 15, method = "bfill") # In row number 8, 15 is replaced by 16.

C:\Users\Dr.Sumedha\AppData\Local\Temp\ipykernel_3516\3307311544.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(to_replace = 15, method = "bfill") # In row number 8, 15 is replaced by 16.

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      16.0
7          8     78.0       14.0   16.0      16.0
8          9      NaN       16.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        16      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

# **** PART 7 ****

# loc()

In [68]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample2.csv")
df.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [69]:
df.loc[3]

Roll No.              4
Section               C
Branch             MECH
Physics            45.0
Chemistry          26.0
Maths              27.0
Computer           28.0
DOB          04-01-2001
Name: 3, dtype: object

In [70]:
df.loc[[5,6,7,8]]

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
5         6       A    ECE     90.0        NaN   29.0      30.0  06-01-2001
6         7       B     CS     12.0       13.0   14.0      15.0  07-01-2001
7         8       C    NaN     78.0       14.0   15.0      16.0  08-01-2001
8         9       A    ECE      NaN       15.0   16.0      17.0  09-01-2001

In [71]:
df.loc[5, 'Physics']  # physics marks of 5th roll number.

np.float64(90.0)

In [72]:
df.loc[5:15, 'Chemistry']  #chemistry marks from 5th roll no to 15 roll no

5      NaN
6     13.0
7     14.0
8     15.0
9     16.0
10    17.0
11     NaN
12    23.0
13     NaN
14    43.0
15    44.0
Name: Chemistry, dtype: float64

In [73]:
df.loc[df['Physics']<50]  # All the physics marks are less than 50.

    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
1          2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
3          4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4          5       A     CS     23.0       27.0   28.0      29.0  05-01-2001
6          7       B     CS     12.0       13.0   14.0      15.0  07-01-2001
9         10       A     CS     45.0       16.0   17.0      18.0  10-01-2001
12        13       A     CS     22.0       23.0   24.0      25.0  13-01-2001
15        16       C    NaN     44.0       44.0   44.0      44.0  16-01-2001
16        17       A   MECH     45.0       45.0   45.0      45.0  17-01-2001
17        18       A   MECH     46.0       46.0   46.0      46.0  18-01-2001
18        19       B    ECE     47.0       47.0   47.0      47.0  19-01-2001
19        20       C   MECH     48.0       48.0   48.0      48.0  20-01-2001
20        21       A   MECH     49.0       49.0   49.0      49.0  21-01-2001

In [74]:
df.loc[df['Physics']>80] # only those roll no.s are printed who have got more than 80 marks.

    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
2          3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
5          6       A    ECE     90.0        NaN   29.0      30.0  06-01-2001
11        12       C     CS     88.0        NaN   19.0      20.0  12-01-2001
13        14       A     CS     90.0        NaN    NaN      42.0  14-01-2001

In [75]:
df.loc[df['Physics']>80, ['Maths']] # Math marks those student who have got more than 80 marks in physics.

    Maths
2    26.0
5    29.0
11   19.0
13    NaN

# iloc()

In [76]:
df.iloc[0]

Roll No.              1
Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 0, dtype: object

In [77]:
df.iloc[[0,1,2]]

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001

In [78]:
df.iloc[:,0] #give  All this rows and the first coln.

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
Name: Roll No., dtype: int64

In [79]:
df.iloc[:,1]  # give all the rows and second colm.

0     A
1     A
2     B
3     C
4     A
5     A
6     B
7     C
8     A
9     A
10    B
11    C
12    A
13    A
14    B
15    C
16    A
17    A
18    B
19    C
20    A
21    A
22    B
23    C
24    A
25    A
26    B
27    C
28    A
29    A
Name: Section, dtype: object

In [80]:
df.iloc[0:5,1]  # 0:5 means 0 to 4 so this are the 5 rows and we hauve to print and only the first index coln that means second coln.

0    A
1    A
2    B
3    C
4    A
Name: Section, dtype: object

In [81]:
df.iloc[0:5, 1:4] # first 5 roll numbers but only the 3 colns from first index to 3rd index coln.

  Section Branch  Physics
0       A     CS     56.0
1       A    ECE     23.0
2       B   MECH     89.0
3       C   MECH     45.0
4       A     CS     23.0

# *** PART 8 ***

# GroupBy() Function

In [82]:
branch_group = df.groupby(by = "Branch") # that means group my data frame acc to the branch. by is the parameter.
branch_group

In [83]:
branch_group.groups  # print all the groups that it is form .

{'CS': [0, 4, 6, 9, 11, 12, 13, 26, 27, 28, 29], 'ECE': [1, 5, 8, 10, 14, 18, 22, 25], 'MECH': [2, 3, 16, 17, 19, 20, 21, 23, 24]}

In [84]:
df.groupby(by = ['Branch', 'Section'])  
branch_group.groups

{'CS': [0, 4, 6, 9, 11, 12, 13, 26, 27, 28, 29], 'ECE': [1, 5, 8, 10, 14, 18, 22, 25], 'MECH': [2, 3, 16, 17, 19, 20, 21, 23, 24]}

In [85]:
for group, data_frame in branch_group:  # It contains two things data frame and also groups (All the roll number and  indexs belongs to this cetaguri that is computer science section 'A' will be printed in data form format.)
    print(group)
    print(data_frame)

CS
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0          1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
4          5       A     CS     23.0       27.0   28.0      29.0  05-01-2001
6          7       B     CS     12.0       13.0   14.0      15.0  07-01-2001
9         10       A     CS     45.0       16.0   17.0      18.0  10-01-2001
11        12       C     CS     88.0        NaN   19.0      20.0  12-01-2001
12        13       A     CS     22.0       23.0   24.0      25.0  13-01-2001
13        14       A     CS     90.0        NaN    NaN      42.0  14-01-2001
26        27       B     CS     55.0       34.0   34.0      55.0  27-01-2001
27        28       C     CS     56.0       35.0   35.0       NaN  28-01-2001
28        29       A     CS     57.0       36.0   36.0      66.0  29-01-2001
29        30       A     CS     58.0       37.0   37.0      43.0  30-01-2001
ECE
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
1          2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
5          6       A    ECE     90.0        NaN   29.0      30.0  06-01-2001
8          9       A    ECE      NaN       15.0   16.0      17.0  09-01-2001
10        11       B    ECE      NaN       17.0   18.0      19.0  11-01-2001
14        15       B    ECE      NaN       43.0   43.0      43.0  15-01-2001
18        19       B    ECE     47.0       47.0   47.0      47.0  19-01-2001
22        23       B    ECE     51.0       51.0   51.0      51.0  23-01-2001
25        26       A    ECE     54.0       33.0   33.0      54.0  26-01-2001
MECH
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
2          3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3          4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
16        17       A   MECH     45.0       45.0   45.0      45.0  17-01-2001
17        18       A   MECH     46.0       46.0   46.0      46.0  18-01-2001
19        20       C   MECH     48.0       48.0   48.0      48.0  20-01-2001
20        21       A   MECH     49.0       49.0   49.0      49.0  21-01-2001
21        22       A   MECH     50.0       50.0   50.0      50.0  22-01-2001
23        24       C   MECH     52.0       52.0   52.0      52.0  24-01-2001
24        25       A   MECH     53.0        NaN    NaN      53.0  25-01-2001

# Merge()Function

In [86]:
df1 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Physics':[34,67,34,89,12]}) 
df1

   Roll No.  Physics
0         1       34
1         2       67
2         3       34
3         4       89
4         5       12

In [87]:
df2 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Chemistry':[78,33,39,81,90]}) 
df2

   Roll No.  Chemistry
0         1         78
1         2         33
2         3         39
3         4         81
4         5         90

In [88]:
pd.merge(df1, df2, on = 'Roll No.')

   Roll No.  Physics  Chemistry
0         1       34         78
1         2       67         33
2         3       34         39
3         4       89         81
4         5       12         90

In [89]:
pd.merge(df2, df1, on = 'Roll No.')

   Roll No.  Chemistry  Physics
0         1         78       34
1         2         33       67
2         3         39       34
3         4         81       89
4         5         90       12

In [90]:
pd.merge(df1,df2)

   Roll No.  Physics  Chemistry
0         1       34         78
1         2       67         33
2         3       34         39
3         4       89         81
4         5       12         90

In [91]:
pd.merge(df1,df2) # if Roll no. is a intersecting coln if i have intersecting coln thn donot need to provide on parameter .

   Roll No.  Physics  Chemistry
0         1       34         78
1         2       67         33
2         3       34         39
3         4       89         81
4         5       12         90

In [92]:
df3 = pd.DataFrame({'Roll No.':[1,2,3,6,7], 'Physics':[34,67,34,89,12]}) # when run  
df4 = pd.DataFrame({'Roll No.':[1,2,3,8,9], 'Chemistry':[34,67,34,89,12]})

In [93]:
pd.merge(df3,df4) # when run pd.merge(df3,df4) it is going to take only those roll numbers who are intersecting.1,2,3 roll numbers are intersecting.

   Roll No.  Physics  Chemistry
0         1       34         34
1         2       67         67
2         3       34         34

In [94]:
pd.merge(df3,df4,how = 'left')

   Roll No.  Physics  Chemistry
0         1       34       34.0
1         2       67       67.0
2         3       34       34.0
3         6       89        NaN
4         7       12        NaN

In [95]:
pd.merge(df3,df4,how = 'right')

   Roll No.  Physics  Chemistry
0         1     34.0         34
1         2     67.0         67
2         3     34.0         34
3         8      NaN         89
4         9      NaN         12

In [96]:
pd.merge(df3,df4,how = 'outer')

   Roll No.  Physics  Chemistry
0         1     34.0       34.0
1         2     67.0       67.0
2         3     34.0       34.0
3         6     89.0        NaN
4         7     12.0        NaN
5         8      NaN       89.0
6         9      NaN       12.0

# *** PART 9 ***

# append()Function

In [97]:
df1 = pd.DataFrame({'Roll No.':[1,2,3,4,5], 'Math':[45,78,45,90,66],'Physics':[33,67,12,90,44]})
df2 = pd.DataFrame({'Roll No.':[6,7,8,9,10], 'Math':[78,73,45,90,69], 'Physics':[23,67,88,0,98]})
print(df1)
print(df2)

   Roll No.  Math  Physics
0         1    45       33
1         2    78       67
2         3    45       12
3         4    90       90
4         5    66       44
   Roll No.  Math  Physics
0         6    78       23
1         7    73       67
2         8    45       88
3         9    90        0
4        10    69       98

In [98]:
df3 = pd.concat([df1, df2],ignore_index=True) # df1.append(df2) df2 is printed after df1.

df1.append(df2, ignore_index=True) # chemistry is there in df1 but not there in df2 so in output all the values of chemistry is taken null.

df1.append(df2, ignore_index=True, sort=True)

*** PART 10 ***

# Pivot Table

In [99]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Desktop\New folder (2)\sample2.csv")
df.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [100]:
print(df.columns)

Index(['Roll No.', 'Section', 'Branch', 'Physics', 'Chemistry', 'Maths',
       'Computer', 'DOB'],
      dtype='object')

In [103]:
pd.pivot_table(df, index='Branch', aggfunc='size')

Branch
CS      11
ECE      8
MECH     9
dtype: int64

In [106]:
pd.pivot_table(df, index='Branch', values='Physics', aggfunc='mean')

          Physics
Branch
CS      51.090909
ECE     53.000000
MECH    53.000000

In [108]:
pd.pivot_table(df, index='Branch', values='Chemistry', aggfunc='mean')

        Chemistry
Branch
CS      30.888889
ECE     32.857143
MECH    42.625000

In [ ]:
pd.pivot_table(df, index='Branch', aggfunc='sum')  # agg = sum -> sum of all chemistry number ,sum of all physics numbers.

,Chemistry,Computer,DOB,Maths,Physics,Roll No.,Section
Branch,,,,,,,
CS,278.0,372.0,01-01-200105-01-200107-01-200110-01-200112-01-...,302.0,562.0,176,AABACAABCAA
ECE,230.0,287.0,02-01-200106-01-200109-01-200111-01-200115-01-...,262.0,265.0,111,AAABBBBA
MECH,341.0,398.0,03-01-200104-01-200117-01-200118-01-200120-01-...,343.0,477.0,154,BCAACAACA

In [ ]:
pd.pivot_table(df, index='Branch', aggfunc='count') # How many students are there. there are 9 students in cs who are given chemistry paper.

        Chemistry  Computer  DOB  Maths  Physics  Roll No.  Section
Branch
CS              9        10   11     10       11        11       11
ECE             7         8    8      8        5         8        8
MECH            8         9    9      8        9         9        9

In [ ]:
pd.pivot_table(df, index='Branch', aggfunc='max') # eg -> 57 is highest marks in cs for chemistry subject.

        Chemistry  Computer         DOB  Maths  Physics  Roll No. Section
Branch
CS           57.0      66.0  30-01-2001   58.0     90.0        30       C
ECE          51.0      54.0  26-01-2001   51.0     90.0        26       B
MECH         52.0      53.0  25-01-2001   52.0     89.0        25       C

In [ ]:
pd.pivot_table(df, index='Branch', columns='Section', values='Maths', aggfunc='mean') # eg-> avg chemistry marks for A section for cs branch.Here null because  it is no  student in C section from the ece branch who is given the chemistry paper.

Section          A      B          C
Branch
CS       33.333333  24.00  27.000000
ECE      25.750000  39.75        NaN
MECH     47.500000  26.00  42.333333